services:
  dyno_atman:
    image: manojm003/dyno_atman:latest
    privileged: true
    environment:
      - DISPLAY=unix:0
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ./path/to/local/workspace:/home/ws/src
      - ./path/to/cache/build:/home/ws/build
      - ./path/to/cache/install:/home/ws/install
      - ./path/to/cache/log:/home/ws/log
    network_mode: host
