services:
  dyno_atman:
    image: manojm003/dyno_atman:latest
    entrypoint: ['bash']
    container_name: 'dyno-atman-cube'
    environment:
      - DISPLAY=unix:0
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - /dev:/dev
    network_mode: host
    working_dir: '/data'
    read_only: false
    privileged: true
    tty: true
