services:
  dyno_atman:
    image: manojm003/dyno_atman:latest
    privileged: true
    environment:
      - DISPLAY=unix:0
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    network_mode: host
    command: ["bash", "-v"]
